spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/cloudDB
spring.datasource.username=cloud
spring.datasource.password=cloud

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true